# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1538a05e841964765813f63f7b82da1dbbbd1df8a5ceca66ee018e85bbd4fba2400f52372ae58dee7a837b92bd92e5aebac85d87100086d9a011de81a516be0

test:
  secret_key_base: f030bcb2cf6bd09607a5d41d4a9f9ac7aee4abb37e8600b2f345014c12344df0881723fe9c7ef635417dc2d489159a03fbd2a25e3ffe46531625b1735dbc9c6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
